---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dnsConfigmap.name }}
  namespace: {{ template "bind9-dns.namespace" . }}
data:
  bind9_hosts_config.yaml: {{ toYaml .Values.dnsConfigmap.data.dnsConfiguration | trim | indent 2 }}
  bind9_reverse_config.yaml: {{ toYaml .Values.dnsConfigmap.data.reverseDnsConfiguration | trim | indent 2 }}
