---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dnsConfigmap.name }}
  namespace: {{ template "bind9-dns.namespace" . }}
data:
  k8s_hosts_config.yaml: {{ toYaml .Values.dnsConfigmap.data.dnsConfiguration | indent 2 }}
  k8s_reverse_config.yaml: {{ toYaml .Values.dnsConfigmap.data.reverseDnsConfiguration | indent 2 }}
