---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "bind9-dns.fullname" . }}
  namespace: {{ template "bind9-dns.namespace" . }}
  labels:
    {{- include "bind9-dns.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bind9-dns.selectorLabels" . | nindent 6 }}
  template: 
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/webmin-config: {{ include (print $.Template.BasePath "/webmin-cm.yaml") . | sha256sum }} 
        checksum/dns-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "bind9-dns.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bind9-dns.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      selector:
        matchLabels:
          {{- include "bind9-dns.selectorLabels" . | nindent 6 }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        - containerPort: 53
          protocol: UDP
          name: dns-udp
        - containerPort: 53
          protocol: TCP
          name: dns-tcp
        env: 
          - name: UPDATE_DNS_CONF
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.bind9.configMapName }}
                key: UPDATE_DNS_CONF
          - name: WEBMIN_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.bind9.configMapName }}
                key: WEBMIN_ENABLED
          - name: WEBMIN_INIT_SSL_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.bind9.configMapName }}
                key: WEBMIN_INIT_SSL_ENABLED
          - name: WEBMIN_INIT_REDIRECT_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.bind9.configMapName }}
                key: WEBMIN_INIT_REDIRECT_PORT
          - name: WEBMIN_INIT_REDIRECT_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.bind9.configMapName }}
                key: WEBMIN_INIT_REDIRECT_ENABLED
          - name: WEBMIN_INIT_REFERERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.bind9.configMapName }}
                key: WEBMIN_INIT_REFERERS
          - name: ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dnsSecret.name }}
                key: ROOT_PASSWORD
        volumeMounts:
          {{- if and .Values.persistence.bind9Data.enabled .Values.persistence.enabled }}
          - name: bind9-data
            mountPath: {{ .Values.bind9.datadir }}
            subPath: {{ ternary "data" (printf "%s/data" .Values.persistence.bind9Data.subPath) (empty .Values.persistence.bind9Data.subPath) }}
          {{- else }}
          - name: bind9-main
            mountPath: {{ .Values.bind9.datadir }}
            subPath: {{ ternary "data" (printf "%s/data" .Values.persistence.subPath) (empty .Values.persistence.subPath) }}
          {{- end }}
          - name: config-files
            mountPath: {{ .Values.dnsConfigmap.configDir }}
            readOnly: true
      volumes:
        - name: bind9-main
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "bind9-dns.fullname" . }}-bind9-pvc{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if and .Values.persistence.bind9Data.enabled .Values.persistence.enabled }}
        - name: bind9-data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.bind9Data.existingClaim }}{{ .Values.persistence.bind9Data.existingClaim }}{{- else }}{{ template "bind9-dns.fullname" . }}-data-pvc{{- end }}
        {{- end }}
        {{- if .Values.dnsConfigmap.name }}
        - name: config-files
          configMap:
            name: {{ .Values.dnsConfigmap.name }}
        {{- end }}
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-peterb83
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1