{{- if and .Values.namespace .Values.createNamespace -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "bind9-dns.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
{{- end }} 