---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dnsSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  ROOT_PASSWORD: {{ default "" .Values.webmin.rootPassword | b64enc | quote }}