apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind9-dns.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bind9-dns.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: bind9-dns-udp
      protocol: UDP
      port: 53
      targetPort: dns-udp
    - name: bind9-dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns-tcp
  {{- if (eq .Values.service.type "LoadBalancer") }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "bind9-dns.selectorLabels" . | nindent 4 }}
