---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.bind9.configMapName }}
  namespace: {{ template "bind9-dns.namespace" . }}
data:
  WEBMIN_ENABLED: '{{ .Values.webmin.enabled }}'
  WEBMIN_INIT_SSL_ENABLED: '{{ .Values.webmin.sslEnabled }}'
  WEBMIN_INIT_REDIRECT_ENABLED: '{{ .Values.webmin.redirectEnabled }}'
  WEBMIN_INIT_REFERERS: '{{ .Values.webmin.referers }}'
  WEBMIN_INIT_REDIRECT_PORT: '{{ .Values.webmin.redirectPort }}'
  UPDATE_DNS_CONF: '{{ .Values.webmin.updateDnsConfig }}'