---
apiVersion: v1
kind: Secret
metadata:
  name: docker-peterb83
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImNHVjBaWEppT0RNNlpHTnJjbDl3WVhSZk5ISnNibWxzWmxCdU5VNU1jMjVyWjJkclUzVXpWa2x0VG5ZNCIKCQl9LAoJCSJyZWdpc3RyeS5rOHMuc2NocmFjay1zZWNvbmV0Lmh1IjogewoJCQkiYXV0aCI6ICJRbUZqYzJGcFVHVjBaWEk2WjJ4d1lYUXRibFJ5VmtGNFJFVlNOMkZLVXpSVmVHOVZaR0k9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-secret
type: Opaque
data:
  ROOT_PASSWORD: OEtZMy43em80MDNZbmFiMmIxTnp6eFA4b0pyeEpXNA==
